### ISSUE TITLE
Cannot create bulk animations downward

### ISSUE THREAD

**Issue by jonstvns** [lukas-shawford/tiled-bulk-animations#1]
Attempting to create a bulk animation with the 'd' direction parameter and 0 or 2+ frames results in an exception.

Repro steps:
1. Open `../tilemaps/rpg-urban-tileset.json`
2. Select one or more tiles
3. Run the bulk animation tool with parameters (d, 2, 100) 
4. Exception thrown
 
Test case files: [tilemap-example.zip](https://github.com/sergkr/tiled-bulk-animations/files/5123087/tilemap-example.zip)

````
TypeError: Cannot read property 'id' of undefined

Action: Create Animations

Stack Trace:
getFrames@file:///C:/Users/Jon/AppData/Local/Tiled/extensions/bulk-animations/bulk-animations.js:279
createAnimations@file:///C:/Users/Jon/AppData/Local/Tiled/extensions/bulk-animations/bulk-animations.js:46
[elided tail calls]@
execute@file:///C:/Users/Jon/AppData/Local/Tiled/extensions/bulk-animations/bulk-animations.js:84
beginCreateAnimations@file:///C:/Users/Jon/AppData/Local/Tiled/extensions/bulk-animations/bulk-animations.js:24
[elided tail calls]@

Extension Version: 1.0

Tileset Information:
Image width: 458
Image height: 305
Tile width: 16
Tile height: 16
Tile spacing: 1
Margin: 0
````

**Comment by lukas-shawford** [comment]
This was caused by lack of support for tile spacing. Give the new version a try ([v1.1](https://github.com/sergkr/tiled-bulk-animations/releases/tag/v1.1)).
