### ISSUE TITLE
Any vertical multi-select animations fail

### ISSUE THREAD

**Issue by jonstvns** [lukas-shawford/tiled-bulk-animations#2]
Make any vertical selection of tiles, run the tool, get an exception. I suspect this might have to do with the lack of handling for tilemap margin and spacing.

Repro steps:
1. Open ../tilemaps/rpg-urban-tileset.json
2. Select at at least 2 tiles that are not in the same row
3. Run the tool with the parameters (r, 2, 100)
4. Get error stating the max number of frames is negative X

Test case files: [tilemap-example.zip](https://github.com/sergkr/tiled-bulk-animations/files/5123305/tilemap-example.zip)

![image](https://user-images.githubusercontent.com/1030863/91166368-1ecdd200-e687-11ea-9453-a6bb93a5d1e2.png)

**Comment by lukas-shawford** [comment]
Similar to #1, this was due to lack of support for margin/spacing. Let me know if you still see any issues with [v1.1](https://github.com/sergkr/tiled-bulk-animations/releases/tag/v1.1).
