### ISSUE TITLE
Cannot edit right stride or frames when selecting bottom left of tileset

### ISSUE THREAD

**Issue by jerricko** [lukas-shawford/tiled-bulk-animations#7]
When trying to do a "Right" direction animation of a set of tiles at the bottom of a tileset, I cannot change the Right Stride or Frame values. It seems to not be updating properly when switching from the "Down" direction.

![Screen Shot 2022-08-30 at 2 37 36 PM](https://user-images.githubusercontent.com/4205817/187553318-97d831dc-a136-45e0-ac74-4f3c41b4e2c0.png)

**Comment by lukas-shawford** [comment]
I've not been able to reproduce this issue with any of the test tilesets. But obviously that looks incorrect, the frames input evaluated to `nan` and the stride inputs should never allow 0.

Are you able to share the tileset image you were using? And do you remember what sequence of steps (input changes) led to this state?

**Comment by jerricko** [comment]
So it was actually happening to me everywhere and not just the bottom corner like I originally thought. I then found out why you probably couldn't reproduce it as I created a test spritesheet to upload here, because it initially started working for me. So I then compared it to my actual spritesheets and it turns out the problem only happens when the spritesheet's height is longer than it is wider. 

Here's the spritesheet (48x48 tiles) I tested with as well as a recording of me trying to set an animation in the top left, but it causes it to skip every other tile.

![Sprite-0001](https://user-images.githubusercontent.com/4205817/189927086-ce9f1e58-92fb-40bd-a821-3ff7c25bbb97.png)

![CleanShot 2022-09-13 at 08 15 32](https://user-images.githubusercontent.com/4205817/189927317-eb15e798-b062-4bc2-8ed1-c6182080bbb8.gif)

**Comment by lukas-shawford** [comment]
Thanks, I believe I see what the issue is. There used to be a single stride value, but we have broken it out into separate `strideR` and `strideD` values to support the "both" animation direction. Then with the newer dialog additions, we are no longer updating the original `stride` value when changing direction. I did some cleanup to try and get rid of `config.stride` entirely, which should hopefully make it less error-prone.

Try the new release:
[v1.3.1](https://github.com/lukas-shawford/tiled-bulk-animations/releases/tag/v1.3.1)

Let me know if you still see any issues with your actual tileset.

**Comment by jerricko** [comment]
There is still an issue for the bottom sprites. It looks like the max frames doesn't get updated with the new value when switching from Down to Right. If I try to animate the bottom-left sprite, it'll only let me set frames to 1 when I should be able to go to 6.

I am able to animate the upper sprites now so that part seems to be fixed now.

**Comment by lukas-shawford** [comment]
Oh, I see - I think I fixed it. Give this one a try:
[v1.3.2](https://github.com/lukas-shawford/tiled-bulk-animations/releases/tag/v1.3.2)

**Comment by jerricko** [comment]
Yep, that did it! Thank you for taking the time to fix it. This plugin has saved me so much time!
