### ISSUE TITLE
Tileset Menu not Available for v1.9.2

### ISSUE THREAD

**Issue by sankalp-chugh** [lukas-shawford/tiled-bulk-animations#8]
I am using MACOS 10.15.7 and Tiled map editor version 1.9.2.

I tried using this extension but I do not have Tileset menu option. Please see screenshot attached.

![Screen Shot 2022-10-16 at 1 22 52 PM](https://user-images.githubusercontent.com/3764551/196049245-674a0ab0-144e-43f2-ab01-fc3c8f4318fa.png)

Thanks in advance!

**Comment by lukas-shawford** [comment]
The menu entry should appear when you have a tileset (tsx file) open. In the screenshot, you currently have a map (tmx file) open.

**Comment by sankalp-chugh** [comment]
It worked!! Thank you so much. Sorry I am a newbie. Although I want to point out that the options it shows in gif is slightly different from the one it currently shows.

**Comment by lukas-shawford** [comment]
Yeah, I do still need to record a new demo, especially with the [recent improvements to use the new dialog functionality](https://github.com/lukas-shawford/tiled-bulk-animations/pull/6). I'll take a look at that when I have time, but hopefully those options make sense and are clearer than the old prompts used to be.
